### ISSUE TITLE
CtrlP.vim has this change backed out?

### ISSUE THREAD

**Issue by damnskippy** [noscript/ctrlp-hibuff#4]
Will this be reintegrated back into CtrlP.vim at some point?
I think this is a good feature to have.
Thanks.

**Comment by sergey-vlasov** [comment]
Not yet. But until it's done you can use my [ctrlp fork](https://github.com/sergey-vlasov/ctrlp.vim).

**Comment by damnskippy** [comment]
Thanks.

**Comment by damnskippy** [comment]
BTW, have you considered applying the path/name split to files & mru also under CtrlP?  Might be a useful option to have.  People sometimes prefer the split names as it's easier to read in some cases.  Just a thought.  Thanks.

**Comment by sergey-vlasov** [comment]
I would like it myself too but that's outside of hibuff scope. Maybe someone decides to inherit this behavior to other modes.

**Comment by noscript** [comment]
Merged https://github.com/ctrlpvim/ctrlp.vim/pull/54
