### ISSUE TITLE
Where is this plugin part of CtrlP?

### ISSUE THREAD

**Issue by Fixles** [noscript/ctrlp-hibuff#5]
Hi,

I cant find any reference to how your plugin has been integrated into CtrlP? How do I highlight buffers? What else did your plugin do?

Thanks.

**Comment by noscript** [comment]
[My pull request](https://github.com/ctrlpvim/ctrlp.vim/pull/54) caused issues for some users so it wasn't accepted to upstream CtrlP yet. I'm planning to finish the work but I'm still out of time.

You can find the integrated version here https://github.com/noscript/ctrlp.vim For configuration read ```doc/ctrlp.txt```, section ```* Buffer explorer mode```.

**Comment by Fixles** [comment]
OK thanks. People were somehow deleting buffers and having CtrlP take over the window. I just tested your ctrlp repo in linux/vim/terminal and didnt have an issue deleting buffers.

But buffers in CtrlPMixed still arent highlighted. Do I need to configure something to make this work?

Thanks.

**Comment by noscript** [comment]
The main problem was that that highlighting was affecting other modes too.

My integration adds only ```:CtrlPBuffer``` mode, also called ```buffers``` in CtrlP status bar. There is some default highlighting, I guess you just trigger the wrong mode.

**Comment by noscript** [comment]
The plugin has been [merged](ctrlpvim/ctrlp.vim/pull/54) now.

**Comment by noscript** [comment]
The plugin has been [merged](https://github.com/ctrlpvim/ctrlp.vim/pull/54) now.

**Comment by noscript** [comment]
The plugin has been merged now https://github.com/ctrlpvim/ctrlp.vim/pull/54
